name: CI

on:
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: 20

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Fail test
        continue-on-error: true
        uses: ./
        with:
          path: tests

      - run: npm version patch --force
        working-directory: ./tests

      - name: Success test
        id: test
        uses: ./
        with:
          path: tests

      - run: |
          echo "name: ${{ steps.test.outputs.name }}"
          echo "version: ${{ steps.test.outputs.version }}"
          echo "release: ${{ steps.test.outputs.release }}"

          if [[ "${{ steps.test.outputs.name }}" != "check-version-test" ]]; then
            echo "The name output is not correct"
            exit 1
          fi

          if [[ "${{ steps.test.outputs.version }}" != "0.0.1" ]]; then
            echo "The version output is not correct"
            exit 1
          fi

          if [[ "${{ steps.test.outputs.release }}" != "check-version-test_v0.0.1+build.2.zip" ]]; then
            echo "The release output is not correct"
            exit 1
          fi
